### ISSUE TITLE
Information regarding Node?

### ISSUE THREAD

**Issue by flanagansteve** [adambard/learnxinyminutes-docs#3785] opened 2019-11-26 18:03 UTC
It seems like there's a great JS tutorial. I've done a good bit of JS / React but am totally in the dark on Node, and haven't found a good tutorial.

Does the JS tutorial cover everything you need to know about Node fundamentally, and I just need to invest time in learning the setup / devops of a Node application?

Or would it be worthwhile to do a standalone Node tutorial?

**Comment by verhovsky** [comment] 2024-04-19 09:29
Dupe of #433

**Closed by verhovsky** 2024-04-19 09:29 UTC
