### ISSUE TITLE
[smalltalk/en] Content issue

### ISSUE THREAD

**Issue by krono** [adambard/learnxinyminutes-docs#2874] opened 2017-09-27 07:42 UTC
It seems that [smalltalk](smalltalk.html.markdown) is a copy of the [Squeak terse guide](http://wiki.squeak.org/squeak/5699) ([most current version](http://squeak.org/documentation/terse_guide/) ) but in an outdated version. 

I can attest that the Squeak community welcomes exposure, especially here. However, I am unsure about the licensing. At least a pointer to the original guide would be nice

**Comment by Oire** [comment] 2017-09-27 19:27
This is a duplicate of issue #2622. It seems, the Smalltalk tutorial should be rewritten. Thanks!

**Closed by Oire** 2017-09-27 19:27 UTC
