### ISSUE TITLE
[Broken link] PyQT link is 404 (2nd try)

### ISSUE THREAD

**Issue by daleathan** [adambard/learnxinyminutes-docs#2496] opened 2016-10-22 21:23 UTC
Originally submitted as https://github.com/adambard/learnxinyminutes-docs/issues/2417  Which has been closed but not fixed.

Still broken.

Link on front page for PyQT 

![brokenlinkpyqt404](https://cloud.githubusercontent.com/assets/1161914/19622635/cdc2345c-98f9-11e6-8d98-53a71281306b.png)

goes to:
https://learnxinyminutes.com/docs/pyqt/

which shows 404 not found
![404not found](https://cloud.githubusercontent.com/assets/1161914/19622642/f309768a-98f9-11e6-9594-b47ce4a0bb22.png)

should probably go to
https://github.com/adambard/learnxinyminutes-docs/blob/master/pyqt.html.markdown

**Comment by samcv** [comment] 2016-10-26 22:25
This issue is caused by adambard/learnxinyminutes-site/issues/36

There's nothing wrong with the page document.  I list all the pages that are broken by this bug there, which includes this one :)

**Comment by samcv** [comment] 2016-10-27 01:02
I just made a pull request ( adambard/learnxinyminutes-site#38 ) which fixes this issue and also fixes all the other sites mentioned in adambard/learnxinyminutes-site#36 that are broken 👍

**Comment by vendethiel** [comment] 2016-10-27 08:14
Going to close this one in the meantime, thanks!

**Closed by vendethiel** 2016-10-27 08:14 UTC
