### ISSUE TITLE
[javascript] Could add some content/links about ES6

### ISSUE THREAD

**Issue by hzoo** [adambard/learnxinyminutes-docs#939] opened 2015-01-27 02:26 UTC
https://espadrine.github.io/New-In-A-Spec/es6/
https://6to5.org/docs/learn-es6/
https://github.com/lukehoban/es6features

**Comment by adambard** [comment] 2015-02-03 20:29
If Python 3 gets its own article, ES6 could definitely stand alone as well. Anyone in the mood?

**Comment by willmendesneto** [comment] 2015-10-12 04:03
A good idea is add the content of BabelJS project to.

Link: https://babeljs.io/docs/learn-es2015/

**Comment by Oire** [comment] 2017-09-12 23:30
This seems to be a duplicate of #1253. There is a rather large discussion there, so I keep that one open.

**Closed by Oire** 2017-09-12 23:30 UTC
Labels: enhancement

**Comment by hzoo** [comment] 2017-09-12 23:47
Yeah we'll try to update to es2016, etc soon https://github.com/babel/website/issues/994

**Comment by adambrenecki** [comment] 2017-09-13 03:05
There's two good PRs adding ES2015 already, and my intention is to do a bit of editing and merge the best of both; I'd forgotten about this but now that I've been reminded I'll do it this weekend.

Originally when those PRs came up I agreed with @adambard that ES2015 deserved its own article, but now that [all modern browsers support nearly all of it](https://kangax.github.io/compat-table/es6/) I think it's appropriate to merge it into the original, indicating which parts are ES2015-only as appropriate.
