### ISSUE TITLE
[c/en] Incorrect description of extern keyword

### ISSUE THREAD

**Issue by noncombatant** [adambard/learnxinyminutes-docs#2847] opened 2017-09-10 21:43 UTC
// if referring to external variables outside function, must use extern keyword.
int i = 0;
void testFunc() {
  extern int i; //i here is now using external variable i
}

This is not true:

~ $ make test
clang -Wall -Wextra -Werror -O0 -ansi -pedantic -std=c11    test.c   -o test
~ $ ./test 
~ $ echo $?
42
~ $ cat test.c
int i = 42;
int main() {
  return i;
}

**Comment by himanshu81494** [comment] 2017-09-11 06:02
@noncombatant 
You are correct pointing out that in example here use of ```extern``` here is not must.
An ```extern``` variable is used for declaration of a variable that is defined in another translation unit of Codebase. That means the storage for the variable is allocated in another file.

**Comment by adambard** [comment] 2017-09-13 05:21
This all sounds pedantic even by C's standards, does anyone mind if I just say "should" instead?

**Comment by jdjohnston** [comment] 2017-09-14 16:40
@adambard Can you provide a reference to a coding standard that recommends this. My understanding of #extern is that was designed to only refer to an item defined in another compilation unit, not external to an individual function. So, yes without further documentation I would "mind" :) if it was changed to "should".

**Comment by divayprakash** [comment] 2018-11-05 05:18
Closing due to lack of clarity on the issue and possible fix.

**Closed by divayprakash** 2018-11-05 05:18 UTC
