### ISSUE TITLE
[forth/en] Syntax highlighting is a bit of a mess

### ISSUE THREAD

**Issue by quat1024** [adambard/learnxinyminutes-docs#2861] opened 2017-09-17 15:44 UTC
The syntax highlighter seems to think ' delimits a comment, so like, half the page is red x)

![image](https://user-images.githubusercontent.com/2068021/30522407-5aeb5ce0-9b9d-11e7-8a93-6f763a88585e.png)
...
![image](https://user-images.githubusercontent.com/2068021/30522411-65ad6c5e-9b9d-11e7-9663-3728b2c6d999.png)

I also think it's not recognizing ( this syntax ) as a comment.

**Comment by RobRoseKnows** [comment] 2017-09-20 01:11
Which file is this?

**Comment by 0xbf00** [comment] 2017-09-27 19:37
@RobRoseKnows the issue is how the file appears on the website<sup>[0](#footnote0)</sup>

This is not something that can be fixed in this repository. Instead, the syntax highlighting of the underlying site is less than ideal. A related issue has been opened in the other repository<sup>[1](#footnote1)</sup>.

<a name="footnote0">[0]</a>: https://learnxinyminutes.com/docs/forth/
<a name="footnote1">[1]</a>: https://github.com/adambard/learnxinyminutes-site/issues/40

**Comment by Oire** [comment] 2017-09-27 19:57
@0xbf00, thanks a lot! Closed in favor of adambard/learnxinyminutes-site#40.

**Closed by Oire** 2017-09-27 19:57 UTC
