### ISSUE TITLE
racket

### ISSUE THREAD

**Issue by jiangtaoQ** [adambard/learnxinyminutes-docs#2865] opened 2017-09-20 21:28 UTC
Make sure the issue title is prepended with '[language/lang-code]' if the language is
already on the site.
If it's a request for a new language, use: '[Request] [language/lang-code]'

Issues are always welcome. If you are able and willing, we welcome any pull requests
as this is a community powered project.

**Comment by Oire** [comment] 2017-09-20 23:21
@jiangtaoQ, sorry, what's the issue?

**Comment by Oire** [comment] 2017-09-27 20:00
The issue is unclear, closing.

**Closed by Oire** 2017-09-27 20:00 UTC
